version: "3.6"
services:
  eclipse-mosquitto:
    container_name: "eclipse-mosquitto"
    image: "eclipse-mosquitto:latest"
    ports:
      - "1883:1883/tcp"
      - "9001:9001/tcp"
    volumes:
      - "/volume1/docker/mosquitto:/mosquitto"
      - "/volume1/docker/mosquitto/data:/mosquitto/data"
      - "/volume1/docker/mosquitto/data:/mosquitto/log"
    networks:
      hass:
        ipv4_address: 192.168.3.201
    depends_on: 
      home-assistant:
        condition: service_started
  home-assistant:
    container_name: "home-assistant"
    environment:
      - "TZ=UTC"      
      - TAILSCALE_STATE_DIR=/var/lib/tailscale
      - TAILSCALE_SERVE_PORT=8123
      - TAILSCALE_SERVE_MODE=https
      - TAILSCALE_USE_SSH=1
      - TAILSCALE_HOSTNAME=hass
      - "TAILSCALE_AUTHKEY==${TS_AUTHKEY}"
      - "DOCKER_MODS=ghcr.io/tailscale-dev/docker-mod:main"
    hostname: "home-assistant"
    image: "linuxserver/homeassistant:latest"
    restart: "always"
    volumes:
      - "/volume1/docker/synology:/config"        
      - "/volume1/docker/synology/varlib:/var/lib"        # State data will be stored in this directory
      - "/dev/net/tun:/dev/net/tun"                      # Required for tailscale to work
    working_dir: "/config"
    networks:
      hass:
        ipv4_address: 192.168.3.200
    cap_add:
      - NET_ADMIN
      - NET_RAW
  onstar2mqtt:
    container_name: "onstar2mqtt"
    depends_on: 
      eclipse-mosquitto:
        condition: service_started
    environment:      
      - "ONSTAR_DEVICEID=${ONSTAR_DEVICEID}"
      - "ONSTAR_VIN=${ONSTAR_VIN}"
      - "ONSTAR_USERNAME=${ONSTAR_USERNAME}"
      - "ONSTAR_PASSWORD=${ONSTAR_PASSWORD}"
      - "ONSTAR_PIN=${ONSTAR_PIN}"
      - "MQTT_HOST=192.168.3.201"
      - "MQTT_USERNAME="
      - "MQTT_PASSWORD="
    image: "michaelwoods/onstar2mqtt:latest"
    restart: "unless-stopped"
    working_dir: "/app"
    networks:
      - hass
  rinq-mqtt:
    container_name: "rinq-mqtt"
    depends_on: 
      eclipse-mosquitto:
        condition: service_started
    image: "tsightler/ring-mqtt:latest"
    ports:
      - "8554:8554/tcp"
    volumes:
      - "/volume1/docker/ringmqtt:/data"
    networks:
      hass:
        ipv4_address: 192.168.3.202
  pv2mqtt:
    image: ghcr.io/wez/govee2mqtt:latest
    container_name: govee2mqtt
    restart: unless-stopped
    environment:      
      - "GOVEE_EMAIL=${GOVEE_EMAIL}"
      - "GOVEE_PASSWORD=${GOVEE_PASSWORD}"
      - "GOVEE_API_KEY=${GOVEE_API_KEY}"
      - "GOVEE_MQTT_HOST=192.168.3.201"
    networks:
      hass:
        ipv4_address: 192.168.3.205


networks:
  hass:
    driver: macvlan
    driver_opts:
      parent: ovs_eth0
    ipam:
      config:
      - subnet: 192.168.1.0/20
        ip_range: 192.168.3.128/28
        gateway: 192.168.1.1